baseurl: '/'
permalink: pretty
title: 'ReStav Group'
description: "ReStav Group (restavgroup) - Kvalitní stavební a zednické práce v celém Pardubickém kraji. Nabízíme omítky, betonáže, hydroizolace, obklady, dlažby, terénní úpravy a další služby. Spolehlivost a zkušenosti."
url: "https://restavgroup.cz"

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

remote_theme: zerostaticthemes/jekyll-serif-theme

plugins:
  - jekyll-environment-variables
  - jekyll-remote-theme
  - jekyll-seo-tag
  # - jekyll-sitemap # dela problem

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - sitemap.xml
